# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "buildmaster" do |buildmaster|
    buildmaster.omnibus.chef_version = :latest
    buildmaster.vm.box = "opscode-ubuntu-12.04"
    buildmaster.vm.hostname = "buildmaster"
    buildmaster.vm.network :private_network, ip: "192.168.43.2"
    buildmaster.vm.network :forwarded_port, guest: 8080, host: 8080
  end

  config.vm.define "buildslave01" do |buildslave01|
    buildslave01.omnibus.chef_version = :latest
    buildslave01.vm.box = "opscode-ubuntu-12.04"
    buildslave01.vm.hostname = "buildslave01"
    buildslave01.vm.network :private_network, ip: "192.168.43.3"
    buildslave01.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end

  config.vm.define "buildslave02" do |b2|
    b2.omnibus.chef_version = :latest
    b2.vm.box = "opscode-ubuntu-14.04"
    b2.vm.hostname = "buildslave02"
    b2.vm.network :private_network, ip: "192.168.43.7"
    b2.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end
  end

  # Scratch VM
  config.vm.define "scratch" do |scratch|
    scratch.omnibus.chef_version = :latest
    scratch.vm.box = "opscode-ubuntu-12.04"
    scratch.vm.hostname = "scratch"
    scratch.vm.network :private_network, ip: "192.168.43.6"
  end

end
