# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "buildmaster" do |buildmaster|
    buildmaster.omnibus.chef_version = :latest
    buildmaster.vm.box = "opscode-ubuntu-12.04"
    buildmaster.vm.hostname = "buildmaster"
    buildmaster.vm.network :private_network, ip: "192.168.43.2"
    buildmaster.vm.network :forwarded_port, guest: 8080, host: 8080
  end

  config.vm.define "buildslave01" do |buildslave01|
    buildslave01.omnibus.chef_version = :latest
    buildslave01.vm.box = "opscode-ubuntu-12.04"
    buildslave01.vm.hostname = "buildslave01"
    buildslave01.vm.network :private_network, ip: "192.168.43.3"
  end

  # Dev environment for Rails apps
  config.vm.define "rdev" do |rdev|
    rdev.omnibus.chef_version = :latest
    rdev.vm.box = "opscode-ubuntu-12.04"
    rdev.vm.hostname = "rdev"
    rdev.vm.network :private_network, ip: "192.168.43.4"
    rdev.vm.synced_folder "../rails_projects", "/rails_projects"
  end

  # Test environment for Rails apps
  config.vm.define "rtest" do |rtest|
    rtest.omnibus.chef_version = :latest
    rtest.vm.box = "opscode-ubuntu-12.04"
    rtest.vm.hostname = "rtest"
    rtest.vm.network :private_network, ip: "192.168.43.5"
  end

  # Scratch VM for looking at intercity/rails cookbook
  config.vm.define "scratch" do |scratch|
    scratch.omnibus.chef_version = :latest
    scratch.vm.box = "opscode-ubuntu-12.04"
    scratch.vm.hostname = "scratch"
    scratch.vm.network :private_network, ip: "192.168.43.6"
  end

end
